dist: trusty

language: node_js

sudo: required

node_js:
  - node

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - WWW_FOLDER="/var/www"
    - VHOST_FQDN="travis.local"
    - VHOST_FOLDER="$WWW_FOLDER/travis"
    - FCGI_FOLDER="$WWW_FOLDER/fcgi-bin"


#    - VHOST_FILE="$TRAVIS_BUILD_DIR/test/.travis/apache.vhost"
#    - PHP_INI_FILE="$TRAVIS_BUILD_DIR/test/.travis/php.ini"
#    - PHP_FCGI_FILE="$TRAVIS_BUILD_DIR/test/.travis/php5.fcgi"

    - VHOST_DEF_CONF="/etc/apache2/sites-available/001-travis.conf"
    - PHP_INI_FILE="/etc/php/5.6/cgi/php.ini"

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
        key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C'
    packages:
      - apache2
      - apache2-suexec
      - libapache2-mod-fcgid
      - php5.6-cgi
      - php5.6-cli
      - php5.6-common
      - php5.6-curl
      - php5.6-gd
      - php5.6-intl
      - php5.6-json
      - php5.6-mbstring
      - php5.6-mcrypt
      - php5.6-mysql
      - php5.6-opcache
      - php5.6-readline
      - php5.6-xml

before_install:
  #

install:
  #

before_script:
  # Setup VHost folder
  - sudo mkdir $VHOST_FOLDER
  - sudo chown $USER:$USER $VHOST_FOLDER
  - cp $TRAVIS_BUILD_DIR/test/.travis/index.php $VHOST_FOLDER/

  # Setup FCGID folder
  - sudo mkdir $FCGI_FOLDER
  - sudo chown $USER:$USER $FCGI_FOLDER
  - sudo chmod 755 $FCGI_FOLDER
  - cp $TRAVIS_BUILD_DIR/test/.travis/php5.fcgi $FCGI_FOLDER
  - chmod 755 $FCGI_FOLDER/php5.fcgi

  # Setup php
  - sudo cp -f $TRAVIS_BUILD_DIR/test/.travis/php.ini $PHP_INI_FILE

  # Configure Apache
  - sudo a2enmod alias actions rewrite fcgid suexec include
  - sudo cp -f $TRAVIS_BUILD_DIR/test/.travis/apache.vhost $VHOST_DEF_CONF
  - sudo sed -e "s,PATH,$VHOST_FOLDER,g" --in-place $VHOST_DEF_CONF
  - sudo sed -e "s,UID,$UID,g" --in-place $VHOST_DEF_CONF
  - sudo sed -e "s,GID,$(echo $GROUPS),g" --in-place $VHOST_DEF_CONF
  - sudo sed -e "s,VHOST_FQDN,$VHOST_FQDN,g" --in-place $VHOST_DEF_CONF

  # Configure hosts file
  - echo "127.0.0.1       $VHOST_FQDN" | sudo tee -a /etc/hosts

  - sudo a2ensite 001-travis
  - sudo service apache2 reload

  # Temp test scripts
  - $TRAVIS_BUILD_DIR/test/.travis/before_script.sh


script:
#  - npm test
  - echo "TEST GOES HERE ;)"

services:
  - mysql

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: change