dist: trusty

language: node_js

sudo: required

node_js:
  - node

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - WWW_FOLDER="/var/www"
    - VHOST_FQDN="travis.local"
    - VHOST_FOLDER="$WWW_FOLDER/travis"
    - FCGI_FOLDER="$WWW_FOLDER/fcgi-bin"
    - VHOST_DEF_CONF="/etc/apache2/sites-available/001-travis.conf"
    - PHP_INI_FILE="/etc/php/5.6/cgi/php.ini"

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
        key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C'
    packages:
      - apache2
      - apache2-suexec
      - libapache2-mod-fcgid
      - php5.6-cgi
      - php5.6-cli
      - php5.6-common
      - php5.6-curl
      - php5.6-gd
      - php5.6-intl
      - php5.6-json
      - php5.6-mbstring
      - php5.6-mcrypt
      - php5.6-mysql
      - php5.6-opcache
      - php5.6-readline
      - php5.6-xml

before_install:
  #

install:
  #

before_script:
  # Setup VHost folder
  - sudo mkdir $VHOST_FOLDER
  - sudo chown $USER:$USER $VHOST_FOLDER

  # Setup FCGID folder
  - sudo mkdir $FCGI_FOLDER
  - sudo chown $USER:$USER $FCGI_FOLDER
  - sudo chmod 755 $FCGI_FOLDER
  - cp $TRAVIS_BUILD_DIR/test/.travis/php5.fcgi $FCGI_FOLDER
  - chmod 755 $FCGI_FOLDER/php5.fcgi

  # Setup php
  - sudo cp -f $TRAVIS_BUILD_DIR/test/.travis/php.ini $PHP_INI_FILE

  # Configure Apache
  - sudo a2enmod alias actions rewrite fcgid suexec include
  - sudo cp -f $TRAVIS_BUILD_DIR/test/.travis/apache.vhost $VHOST_DEF_CONF
  - sudo sed -e "s,PATH,$VHOST_FOLDER,g" --in-place $VHOST_DEF_CONF
  - sudo sed -e "s,UID,$UID,g" --in-place $VHOST_DEF_CONF
  - sudo sed -e "s,GID,$GROUPS,g" --in-place $VHOST_DEF_CONF
  - sudo sed -e "s,VHOST_FQDN,$VHOST_FQDN,g" --in-place $VHOST_DEF_CONF
  - sudo a2ensite 001-travis
  - sudo service apache2 restart

  # Configure hosts file
  - echo "127.0.0.1       $VHOST_FQDN" | sudo tee -a /etc/hosts

  # Configure Mysql
  - mysql -u root -e 'CREATE DATABASE suitecrm;'

  # Setup VHost folder content
  # - cp $TRAVIS_BUILD_DIR/test/.travis/index.php $VHOST_FOLDER

  # Setup SuiteCRM in VHost folder
  - git clone https://github.com/salesagility/SuiteCRM.git $VHOST_FOLDER
  - cd $VHOST_FOLDER
  - git checkout tags/v7.8.3
  - cp $TRAVIS_BUILD_DIR/test/.travis/travis_config_si.php config_si.php
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar install --no-interaction
  - php tests/testinstall.php


  # Temp test scripts
  - $TRAVIS_BUILD_DIR/test/.travis/before_script.sh

script:
#  - npm test
  - echo "TEST GOES HERE ;)"

services:
  - mysql

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: change