language: node_js

sudo: required

node_js:
  - node

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - VHOST_FILE="apache.vhost"
    - PHP_INI_FILE="%TRAVIS_BUILD_DIR%/test/.travis/php.ini"

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
        key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C'
    packages:
      - apache2
      - libapache2-mod-fcgid
      - php5.6-cli
      - php5.6-cgi
      - php5.6-curl
      - php5.6-gd
      - php5.6-intl
      - php5.6-json
      - php5.6-mcrypt
      - php5.6-mbstring
      - php5.6-mysql
      - php5.6-xml

before_install:

install:

before_script:
  - test/.travis/before_script.sh

script:
#  - npm test
  - echo "TEST GOES HERE ;)"

services:
  - mysql

branches:
  only:
    - master
